### ISSUE TITLE
Operator uninstall

### ISSUE THREAD

**Issue by jgawor** [kabanero-io/kabanero-operator#103]
Ensure the operator can be cleanly uninstalled (via doc or code updates).

Right now it appears the operator cannot be cleanly uninstalled. It might be related to https://github.com/knative/serving/issues/4732.

**Comment by kaczyns** [comment]
I'm trying to outline how an un-install should go.  One thing to keep in mind is that we shouldn't delete an object (controller) that provides a finalizer, before deleting objects that need the finalizer to run.  It's just one thing to keep in mind, there are others but this is on my mind as it's come up recently for other reasons.

Steps:
1) Delete `Kabanero` instances.  This should cascade delete `Collection` instances which should in turn delete their respective pipelines, etc.  We could consider having the un-install script just fail if there are instances of `Kabanero` left and ask the user to remove them manually.
2) Delete the Kabanero operator from the kabanero namespace.  This leaves the kabanero finalizer (coming soon to a github near you) available while the `Kabanero` instances are deleted.
3) Delete the `Kabanero` and `Collection` CRDs.
4) Delete the Tekton `Config` object, if we created it.  I am thinking that the Kabanero operator will need to annotate this object if we created it, so that we know it's safe to delete it.  Deleting the `Config` object tells Tekton to un-register its CRDs, etc.
5) Delete the Tekton operator.  Again this may need to be annotated.
6) Delete the Tekton `Config` CRD.
7) Delete Knative sources (contrib).  It seems like we can just un-do the yaml we applied, there are no operators here.
8) Delete the Knative serving and eventing marker objects from their respective namespaces.  The behavior of the v0.6 operator is to automatically create these marker objects, so there is no way to know that they were created on behalf of the Kabanero operator.  Deleting these marker objects causes Knative to delete most of its infrastructure.  A future version of KNative operators requires the implementation to create the marker objects, at which point we could annotate them so we know that we should delete them.
9) Delete the Knative operators.  May also need to delete the knative-serving and knative-eventing namespaces at this point.
10) Delete the Knative eventing and serving CRDs that are left.
11) Delete Istio.  This requires some investigation but I suspect at this point it's probably safe to just delete (undo) the Istio yaml that we applied in the install script.

Comments are welcome :-) I am hoping that this avoids some of the hangs we've been seeing on uninstall.

**Comment by kaczyns** [comment]
A sample uninstall script is provided in kabanero-io/kabanero-foundation#76 which should be useable as-is in most circumstances.  Please let us know if you have any trouble with it.
