### ISSUE TITLE
Add kAppNav to Kabanero operator

### ISSUE THREAD

**Issue by cvignola** [kabanero-io/kabanero-operator#116]
The goal is for kAppNav to get installed as part of Kabanero install. 

kAppNav install instructions are here:  https://github.com/kappnav/README

Proposed timeline is iteration 19.18.  If too soon, 19.19 is also acceptable.

**Comment by rlcundiff** [comment]
kappnav v0.1.0 is complete.  Images are in DockerHub and master branches in github are tagged as v0.1.0.

**Comment by kaczyns** [comment]
I am re-opening this epic.  The kappnav deploy needs to move to a cluster scope.  It will be installed by the install script and should be optional, controlled by an environment variable.  If the environment variable is not set, the user should be prompted (as is done for the master default subdomain currently).

The script should deploy the kappnav operator and a kappnav instance.  The kappnav instance should be set up so that it does not modify the OKD console.  I am not sure what the attributes are in the CRD that control this but I am told that they exist.

It's possible that we come back later and modify the kappnav instance to "share" the OKD console with Kabanero.  As I understand it there are several extension points on the console and we could divide them up such that someone can still get to the Kabanero doc page easily when first installed, but also have the kappnav in a convenient place so that it can be used frequently during app development.

**Comment by marikaj123** [comment]
kAppNav is done.  
Operator team: Has work to do in the Kabanero install script to pull it in.  
Kabanero.io website team:  Needs to be updated to introduce kAppNav and point to kappnav.io.

**Comment by alohr51** [comment]
@marikaj123 There should be separate issues for the operator team and the website team work you mentioned.

**Comment by marikaj123** [comment]
@alohr51 @kaczyns - Can we ad them as child issues to this Epic, please.

**Comment by dianak2016** [comment]
I think you should use the epic targeted for Oct 7 which is https://github.com/kabanero-io/roadmap/issues/70 to attach child issues scoped to this release.

**Comment by marikaj123** [comment]
Sure, we can do that.  I have included this epic as a child of the #70. @kaczyns and @alohr51 can you please add your child issues under kabanero-io/roadmap#70.

**Comment by kaczyns** [comment]
I am modifying this issue to look less like an epic now that there is epic kabanero-io/roadmap#70 tracking this work.

**Comment by kaczyns** [comment]
This was delivered in kabanero-io/kabanero-foundation#90
