### ISSUE TITLE
Dynamically update the operator status based on dependent service status.

### ISSUE THREAD

**Issue by mezarin** [kabanero-io/kabanero-operator#134]
The operator should watch for resource dependency updates and update it's status dynamically.

**Comment by kaczyns** [comment]
Specifically we are talking about watching the `KNativeServing` and `KNativeEventing` objects in their respective namespaces, the `Config` object for Tekton, and the `Deployment` objects for the landing page, CLI and Appsody operator.

**Comment by stephenkinder** [comment]
@mezarin @kaczyns it appears an issue related to this was merged?  Should this be closed or is this still an issue.

**Comment by mezarin** [comment]
@stephenkinder if you are referring to the issue related merged PR 111, this is a follow up work on that issue.

**Comment by kaczyns** [comment]
Things have changed a bit since this issue was opened.  I'm not sure we'll be able to do everything we want to do, due to some limitations in controller-runtime (ok they are probably not limitations but I lack the overall understanding of controller-runtime to be able to say what is expected).

Lets start with what we can definitely do.  When the Kabanero controller is created, it should watch the following objects, if the Kabanero instance is the owner (see the existing watch on `Collection` to see how to do this):
* Deployments
* Routes
* Services

Watching those three things, will let the Kabanero controller re-create any of these things that are inadvertently deleted or modified.

Watching the following cluster-scoped object should also be possible:
* Tekton `Config` (aka config.operator.tekton.dev)

What I'm not sure about, are the namespace scoped objects in other namespaces.  I know that the controller runtime (at least the 0.1.x controller-runtime) would not cache objects outside of the namespace where the controller was deployed, and therefore you had to use `unstructured` when getting these objects to force the controller-runtime to ignore the cache.  For watches, I don't see a way around the cache.  Now, we're on controller-runtime 0.2.0 now, so maybe things have changed.  We should try watching something like `KnativeServing` in the `knative-serving` namespace.  Actually, I don't see a way to specify a namespace on the watch, so perhaps we should investigate that part first (how to specify a namespace).  If there's no way to specify a namespace, then I don't see how we could do this part.  If we can watch in another namespace, then we should also be watching:
* KnativeServing in the knative-serving namespace

I'm sort of torn over what to watch for Appsody... it would probably end up being a deployment in another namespace, but that is going to generate a lot of "misses" and probably not worth it.  Perhaps `subscriptions` in another namespace, to catch the Appsody subscription coming and going?

**Comment by kaczyns** [comment]
I think we've come to the conclusion that we can watch what we can watch in our own namespace.  Watching things in other namespaces is hard or impossible until we have a cluster scoped operator.  I am closing this issue for now as "un-implementable" and we'll re-visit this idea when we have a cluster scoped operator or controller.
