### ISSUE TITLE
Tekton Config in dependencies.yaml can cause: no match for kind

### ISSUE THREAD

**Issue by dacleyra** [kabanero-io/kabanero-operator#141]
https://github.com/kabanero-io/kabanero-operator/blob/master/deploy/dependencies.yaml#L1037

The Config is created immediately after the CRD

1. Remove?
2. Manage Config object with kabanero operator?

**Comment by mtamboli** [comment]
It seems like this issue causes Kabanero install script to fail. It is not a good experienceand used does not know that re-running the script will work. So it seems must fix or 0.1 release.

**Comment by kaczyns** [comment]
Based on previous conversations it seems like creating the `Config` object in the operator is the correct thing to do (if it's not already there).  An alternative would be to wait for the Config CRD to be available before creating the Config instance in the script.

@mtamboli I'm don't think this is containable in release-0.1.  Is there another less-important issue we can pull out?

**Comment by mtamboli** [comment]
@kaczyns @dacleyra Is it possible to avoid this condition by some workaround  in the install scriptfor this release-0.1? Like some wait mentioned above in the install script. User is clueless when the install fails on what to do.

**Comment by stephenkinder** [comment]
@mtamboli @garypicher Monica, would a "README.md" update in Kabanero Installation guide section with known workarounds suffice for this release?

**Comment by kyleschlosser** [comment]
I think we can just put a retry/reapply into the script for now?

**Comment by dacleyra** [comment]
Put in a loop retry reapply 

Do we want to keep this open for the root issue, or is that tracked elsewhere?

**Comment by garypicher** [comment]
A similar workaround was made downstream, so I don't believe this issue is still needed for release-0.1.x.

**Comment by stephenkinder** [comment]
I took the status off of the bug because this issue isn’t blocking any release at the moment.   Do we expect we can fix in the operator? @kaczyns ?

**Comment by kaczyns** [comment]
@stephenkinder We do plan to remove the creation of the tekton `Config` object from dependencies.yaml or release.yaml or whatever flavor we're using, and have the Kabanero operator create it instead.  However we need to be careful when we do this, because now we have a different problem.  The Tekton `Config` is what creates the Tekton controllers and Tekton CRDs (such as `Pipeline` and `Task`).  The Kabanero operator will then have to wait for these CRDs to be available before deploying anything else (like collections).  Further, the Tekton dashboard and webhook extensions deploy a sample `Pipeline` and `Task`, which isn't going to work if we move the `Config` out of the install script and into the operator.  We'll have to move the deploy of the dashboard and webhook extension to the operator as well.

So it's a big can of worms really if we fix this.

**Comment by kaczyns** [comment]
tektoncd/operator#9 is a good start towards moving this configuration out of the install script and into the kabanero controller.  The dashboard extension can now be specified as an `addon` by the tektoncd operator.  AFAIK the webhook extension isn't supported as an addon yet.  

We should consider moving the creation of the tekton `Config` object, the dashboard and webhook to the kabanero controller, but we need to be careful that these objects are not removed when the Kabanero instance is removed.  There could be another Kabanero instance that is using it (we can argue whether this is true in practice or not).  One way we could attempt to solve this problem is by using the owner reference fields on the `Config` object.  Each `Kabanero` that is using the `Config` can make itself an owner (There could be multiple owners).  Any additional artifacts that we have to create (ie the webhook extension bits and pieces), we can set the owner as the `Config` object.  In this way, when the last `Kabanero` object is deleted, the `Config` object and friends would also be deleted. Someone would need to try this out and see if it actually works (it works in my head but that doesn't mean anything).

**Comment by marikaj123** [comment]
@dacleyra - Is the issue ready to close?

**Comment by dacleyra** [comment]
This is solved in the 0.3.0 alpha
