### ISSUE TITLE
Disable landing page

### ISSUE THREAD

**Issue by jgawor** [kabanero-io/kabanero-operator#177]
For integration purposes, need a way to disable the landing page.

**Comment by kaczyns** [comment]
@jgawor do you have a preference how we do this?

**Comment by kaczyns** [comment]
@tspewak I'd like to try and find a simple solution if we can.  @kyleschlosser has already outlined some more involved solutions such as the admission controller which I don't think we're ready to tackle yet.

The real problem here is that there is (or there is almost) and `enabled` property in the model (Kabanero kind) that would turn the landing page on or off, but we want the default to be `true` and that isn't possible for a `bool` type since the default for a `bool` is `false`.  We don't want the user to have to say that the landing page is enabled explicitly in their Kabanero document.

First thing to try - @mezarin thinks he remembers that if you add a `*bool` in the model instead of `bool` that you'll get either true / false / nil instead of just true / false.  If this is true, then we can say that `nil` is the same as `true`.  In PR #184 @kyleschlosser added many fields to the model, including `enabled` for several components.  See [this code](https://github.com/kabanero-io/kabanero-operator/blob/28388364bd0d0b9d4686aaec5a47ed077e2b78f9/pkg/apis/kabanero/v1alpha1/kabanero_types.go#L83).  Lets try uncommenting this and changing it to a `*bool` instead of `bool`.  If we do indeed get a true / false / nil then I think we have our desired default behavior because we can treat a `nil` as `true`.  We just need to be careful that we can't read the value from `nil`.

Second thing to try would be to treat `enabled` as a `string` instead of a `bool` in the same place.  We can treat the empty string as `true`.  If we read an invalid value we'd have to issue a message saying so, and treat it as `true`.  Perhaps also update the `Status` message with this information?  I don't know.

Third thing would be to investigate if there's some way to modify the `json` annotation for that line into saying that `true` is the default value, and to always write it.  I doubt this is possible but it's worth investigating if the first two options don't work out.

And if none of this works out then we'll have to wait for the admission controller.  I don't want to introduce a name into the model that is not consistent (ie I don't want to call this attribute `disabled` just so that the default of `false` makes sense, when the rest of the like-named attributes are called `enabled`).

**Comment by tspewak** [comment]
*bool will work

**Comment by kaczyns** [comment]
#191 is merged
