### ISSUE TITLE
Implement operator function to honor cliServices: tag and sub fields 

### ISSUE THREAD

**Issue by davco01a** [kabanero-io/kabanero-operator#192]
Implement operator function to honor cliServices: tag and sub fields in the Kabanero document ( CRD )

e.g.

![image](https://user-images.githubusercontent.com/7747967/65250640-df385680-dac3-11e9-8600-4910154c788c.png)

**Comment by kaczyns** [comment]
Just to be clear, the requirement is that the CLI team needs to be able to test new versions of the CLI microservice container in the confines of Kabanero without rebuilding the Kabanero operator.  The configuration that Dave includes above is already present in the model, we just need to hook the code up to it so that the correct CLI container image is generated.

**Comment by davco01a** [comment]
@kyleschlosser ^^

**Comment by kaczyns** [comment]
Fixed by #200

**Comment by kaczyns** [comment]
It looks like all is well when the deployment is created, but if the image tag changes, the deployment is not updated.

**Comment by kaczyns** [comment]
Fixed by #200 and #203
