### ISSUE TITLE
Allow patched version of the appsody operator

### ISSUE THREAD

**Issue by arthurdm** [kabanero-io/kabanero-operator#204]
Background links:  [comment 1](https://github.com/kabanero-io/kabanero-operator/pull/190#issuecomment-535616901) and [comment 2](https://github.com/kabanero-io/kabanero-operator/pull/190#issuecomment-535627923)

Net is:  would be nice if Kabanero could either: (a) automatically pick up patched versions of the appsody operator, or (b) allowed customers to update which version of the operator kab installs (via initial config).

For either (a) or (b) it means a change for the kab operator to not ship with hardcoded YAMLs, but instead download them from the appsody GitHub release - this is what the appsody CLI does today when it needs to install the appsody operator.  

@kaczyns had good comments in terms of a `0.2` image, the only issue is that our appsody operator GitHub release is a combination of the controller image plus the YAMLs around it - so a change between releases `0.2.0` and `0.2.1` could be outside of the controller image (e.g. could be a change in the `appsody-app-operator.yaml` file.

**Comment by kaczyns** [comment]
The Kabanero operator has been trying to use a pattern where the components it installs provide a template yaml that contains all the pieces that they need (role, sa, binding, deployment, service, route, etc).  We then apply a series of substitutions to it (for example, the specific container image, a namespace name, etc) and apply it.  This lets us use the same yaml for several releases of the component, until that component evolves to the point that it needs a new template yaml.  We refer to this tempate yaml for a component as an orchestration, and there is a new version of the orchestration each time the template needs a substantial change.

The fact that the surrounding yamls can change in a patch release makes it not sound so much like a patch release, and more like a minor version change.  It also makes it more difficult to debug problems between the components, when the pieces are changing.  I know that there are projects that consume Kabanero that depend on the pieces being stable at a particular Kabanero version (ie 0.1.2 contains a known set of components that will not change until 0.1.3).

We also try to limit the times we download and apply yaml from the internet to a minimum.  The one place where we do this, which we cannot avoid, is when the collection controller applies the collections.  The collections are hosted on github or GHE and there is no way around downloading them and applying them because the user is free to change them as they see fit.  I know of at least one consumer of Kabanero which downloads all of the container images for the components locally, and this would not be possible if it did not know what to get ahead of time.

These are the concerns that I have with downloading the latest patch release from a well known location at runtime.

The user can do what you're asking today in (b) with the following yaml (and can update it after the fact if they wish):
```yaml
apiVersion: kabanero.io/v1alpha1
kind: Kabanero
metadata:
  name: kabanero
spec:
  version: "0.1.2"
  appsody-operator:
    image: appsody/appsody-operator:0.2.1
```

I know that's less than optimal, but, it does let someone get a patch/fix quickly while waiting for the next patch release of Kabanero which would contain the patched version of Appsody operator.

**Comment by arthurdm** [comment]
thanks @kaczyns - it's good to know that customers could at least update the controller image version.

**Comment by kaczyns** [comment]
@arthurdm Starting with Kabanero 0.3.0, the kabanero-foundation install script will be installing Appsody from the OpenShift operator hub.  The subscription can be set up to upgrade automatically.  So basically when you certify a new version, it would become available and the customer would get it automatically.  Or the customer could choose to have manual approval and select it when they are ready.

Does this resolve the issue?

**Comment by arthurdm** [comment]
thanks @kaczyns - that's great news.  closing the issue.
