### ISSUE TITLE
Update to operator-sdk v0.11.0 (or newer)

### ISSUE THREAD

**Issue by dacleyra** [kabanero-io/kabanero-operator#250]
Require controller-runtime v0.2.0 or newer to support issue #230

**Comment by kaczyns** [comment]
Some more words about this....
The operator-sdk provides the initial dependencies for your project (Gopkg.toml) which include controller-runtime.  The version of operator-sdk that the kabanero-operator was created with, used controller-runtime v0.1.10.  The v0.1 train stops at v0.1.12 (or at least that's where it's stopped right now).

We know of at least one bug that we're currently working around, plus the stuff for #230, that would be fixed by moving up to controller-runtime v0.2.0.  We can't just upgrade controller-runtime by itself, because then anything we do with `operator-sdk` will not work (ie add a new CRD and controller).  The two should be updated together.  Or, we need to stop using `operator-sdk`, and I don't think we're ready to do that yet.

The operator-sdk 0.11.0 includes controller-runtime v0.2.0.  The community has acknowledged that this is a non-trivial migration but one that is going to be necessary.

**Comment by kaczyns** [comment]
This will be included in Kabanero 0.5.0.
