### ISSUE TITLE
Bug:  Nodejs collection was not updated to 0.2.0 after upgrade

### ISSUE THREAD

**Issue by tam512** [kabanero-io/kabanero-operator#286]
- Upgrade Kabanero collection from 0.1.2 to 0.2.0 
- Run a node.js pipeline in Tekton dashboard and I see the build-task has only 2 steps `assemble-extract and build-push` instead of 4 steps `assemble-extract, validate-collection-is-active, build-bud, and build-push` as expected in kabanero 0.2.0 collection
- List collections in kabanero namespace
```
$ oc get collections
NAME                AGE
java-microprofile   15d
java-spring-boot2   15d
nodejs              15d
nodejs-express      15d
nodejs-loopback     15d
```
- describe nodejs collection and see that the URL to kabanero collection is still at v0.1.2
```
$ oc describe collection nodejs
Name:         nodejs
Namespace:    kabanero
Labels:       <none>
Annotations:  <none>
API Version:  kabanero.io/v1alpha1
Kind:         Collection
Metadata:
  Creation Timestamp:  2019-10-22T01:13:21Z
  Generation:          1
  Owner References:
    API Version:     kabanero.io/v1alpha1
    Controller:      true
    Kind:            Kabanero
    Name:            kabanero
    UID:             22d02cdf-f469-11e9-bc10-561e38f530d1
  Resource Version:  435465
  Self Link:         /apis/kabanero.io/v1alpha1/namespaces/kabanero/collections/nodejs
  UID:               233f0663-f469-11e9-a81e-36d350d4d728
Spec:
  Name:     nodejs
  Version:  0.2.5
Status:
  Active Assets:
    Asset Digest:   a59a779825c543e829d7a51e383f26c2089b4399cf39a89c10b563597d286991
    Asset Name:     default
    Status:         active
    URL:            https://github.com/kabanero-io/collections/releases/download/v0.1.2/incubator.common.pipeline.default.tar.gz
  Active Location:  https://github.com/kabanero-io/collections/releases/download/v0.1.2/kabanero-index.yaml
  Active Version:   0.2.5
  Images:
    Id:     nodejs
    Image:  kabanero/nodejs:0.2
Events:     <none>
```

- Other collections were updated to 0.2.0 as an example below with nodejs express

```
$ oc describe collection nodejs-express
Name:         nodejs-express
Namespace:    kabanero
Labels:       <none>
Annotations:  <none>
API Version:  kabanero.io/v1alpha1
Kind:         Collection
Metadata:
  Creation Timestamp:  2019-10-22T01:13:21Z
  Generation:          2
  Owner References:
    API Version:     kabanero.io/v1alpha1
    Controller:      true
    Kind:            Kabanero
    Name:            kabanero
    UID:             22d02cdf-f469-11e9-bc10-561e38f530d1
  Resource Version:  446274
  Self Link:         /apis/kabanero.io/v1alpha1/namespaces/kabanero/collections/nodejs-express
  UID:               233ab5da-f469-11e9-a81e-36d350d4d728
Spec:
  Name:     nodejs-express
  Version:  0.2.7
Status:
  Active Assets:
    Asset Digest:   8586074aafa8a11c322b62a413137a36e33345f809d7fde1b01f8b4f28ddf30e
    Asset Name:     default
    Status:         active
    URL:            https://github.com/kabanero-io/collections/releases/download/0.2.0/incubator.common.pipeline.default.tar.gz
  Active Location:  https://github.com/kabanero-io/collections/releases/download/0.2.0/kabanero-index.yaml
  Active Version:   0.2.7
  Images:
    Id:     nodejs-express
    Image:  kabanero/nodejs-express:0.2
Events:     <none>
```

**Comment by marikaj123** [comment]
@groeges - What would be the right team to provide the fix?

**Comment by groeges** [comment]
@marikaj123 I would think this was an issue related to the upgrade processes whomever wrote that or the operator team (which is where the issue has been raised).

**Comment by kaczyns** [comment]
@tam512 Can you please confirm the following steps to re-create?
1) Install Kabanero 0.1.2 with collections 0.1.2
2) Upgrade to Kabanero 0.2.0 but still using collections 0.1.2
3) Move up to collections 0.2.0
Thanks!

**Comment by kaczyns** [comment]
I will also note that the version of the `nodejs` collection is version `0.2.5` in both collections `0.1.2` and `0.2.0` - how is the operator supposed to know that they are different?

**Comment by jgawor** [comment]
so we changed the pipelines but not the stack and we didn't bump the collection versions? sounds like we have a process issue.

**Comment by marikaj123** [comment]
@groeges - Any ideas you can provide based on the above comments will be helpful.

**Comment by groeges** [comment]
The pipelines are common to all collections. Are we supposed to increase the version of every stack when the common pipelines have changed. We need to review the process on what needs to be done to versions etc when pipelines are changed.

**Comment by groeges** [comment]
@kaczyns The version information in collections is a bit of a mess right now and we are trying to sort it out. The version that is currently provided is the version of the stack (which is the same as the version we get when we pickup the stack from Appsody). 

As a collection is a combination of several things, ie stack, pipelines then we really should have a collection version that should change when components of a collection change. We were going to that but that was deemed unnecessary by some higher power.

The issue we currently have is that the pipelines that are being used today are common to all pipelines, so if a common pipeline changes do we (and Champ) need to go around and change the version of all the collections even if the actual components of the collection haven't changed, ie the stack and the pipelines for a specific stack (these would be different from the common pipelines).

My understanding was that if the kabanero-index.yaml file was changed then you were going to loop through all the information to check if anything had changed and were going to be using the sha256 values that were added for the pipeline tar.gz files to check to see whether the pipelines for the collection had changed, rather than just checking the version had changed.   

I think checking that the sha256 had/hadn't changed would be a better solution, specifically because of the common pipelines being able to change without the actual stack changing. Also a stack may change (the underlying images and templates and stack definition etc) but the common pipelines don't, and I wouldn't expect you to delete and recreate all the pipelines for that stack in this instance.

**Comment by kaczyns** [comment]
@groeges I agree with what you are saying.  I don't think that reliably comparing the sha256 is something that the operator team can contain for 0.3.0.  

I think though that Champ needs something that he can hang his hat on, to know what is actually installed.  It is going to be difficult for him to know which variant of the nodejs stack is actually applied without some kind of a collection version (sure he could look at the checksum that the operator applied and figure it out, but that seems cumbersome).

**Comment by jgawor** [comment]
I agree with @kaczyns - we need a collection version. Or we need to version each component of a collection and make operator to deal with each.

**Comment by marikaj123** [comment]
@groeges - At what release can we provide the collection versioning idea decribed above?

**Comment by groeges** [comment]
@marikaj123 To get this added we need some architectural design etc. As such @kilnerm I in the process of raising an Epic in order to get the entire versioning story sorted out. This will not be able to be done for 0.3.0 and depending on what is required should hopefully be able to be contained in the 0.4.0 release (but this is still to be confirmed and will also depend on length of time to get architectural decisions)

**Comment by groeges** [comment]
@kaczyns @marikaj123 In order to get the NodeJS collection detected as being updated (due to common pipeline changes) when an upgrade is made to Kabanero 0.3.0 we have update the stack version. 

This should resolve this issue for 0.3.0 and the future versioning changes will resolve these scenarios in the future.

**Comment by groeges** [comment]
@marikaj123 The following PR (Collections) updates the NodeJS collection version so that it will be detected during a Kabanero upgrade: https://github.com/kabanero-io/collections/pull/168
Unless there are other changes needed to the Operator for this for 0.3.0 then I think this issue can be closed once tested (will need to spin another Collections and Operators release in order to fully test)

@kaczyns In a future release the Operator may need to change to pickup the Collections version and check that rather than the current Stack version. 

We will raise another issue for this when we have  the versioning strategy for Collections sorted out.
