### ISSUE TITLE
Operator needs to take some action when collection is removed from collection hub 

### ISSUE THREAD

**Issue by mtamboli** [kabanero-io/kabanero-operator#316]
There are 2 case:

**Case 1:** If the URL of collection is updated in the operator. Updated collection does not have a collection which is active now on the operator

**Current Behavior:** Operator still keeps the collection active. Status may change after the CLI does `sync'

**Expected Behavior:**  I expect operator to make the collection inactive. There may be a safety reason to remove a collection and it should not be active if it is deleted in the latest collection hub which is active. At a minimum, there should be some indication that the collection is active despite of not existing in collection hub.

**Case 2:** : Collection hub did not change. Some one just updated the existing release, replacing the yaml file. 
**Expected Behavior:**  In this case, operator may not know about the change. So operator cannot really do anything. `kabanero sync` should deactivate/delete it. 

Would like to know when will the deactivated collection be cleaned up/deleted though if `sync` is only deactivating the collection.

**Comment by kaczyns** [comment]
@mtamboli We expect that the CLI will be used to manage the connection between the connection hub, and the OpenShift cluster.  The expected flow is this:
1) Collection A is present in the collection hub, and is active on the OpenShift cluster.
2) Champ creates a new release of his collection hub, which removes collection A.
3) Champ modifies the Kabanero CR instance to point to the URL of the new collection hub release
4) Kabanero operator processes the new URL and, if configured, activates any new collections in the collection hub.  It does not delete or deactivate any collections that were previously active.
5) Champ uses the CLI to sync collections, at which point the CLI either dectivates or deletes any collections that are active, but no longer present in the collection hub.

An alternative strategy, if Champ is not using the kabanero CLI, would be for Champ to manually delete the collection objects from his OpenShift cluster that are no longer in the collection hub, and  that he no longer wants.  

I think that the CLI should change, to delete (rather than deactivate) collections that are no longer present in the collection hub when a `sync` is performed.  In that case, this issue belongs in the CLI github.

**Comment by marikaj123** [comment]
Issue moved to [kabanero-io/kabanero-command-line-services #96](https://github.com/kabanero-io/kabanero-command-line-services/issues/96) via [**ZenHub**](https://www.zenhub.com/)
