### ISSUE TITLE
Subscription errors on operator

### ISSUE THREAD

**Issue by mtamboli** [kabanero-io/kabanero-operator#348]
Seeing the below errors on the kabanero operator due to mismatch in name:

```
status:
    appsody:
      errorMessage: 'Unable to retrieve the version of installed Appsody operator.
        Error: subscriptions.operators.coreos.com "appsody-operator-certified" not
        found'
```

**Comment by kaczyns** [comment]
The issue here is that the Kabanero operator assumes that the subscription has a specific name.  If it does not find a subscription with that exact name, the operator reports a problem in the Kabanero CR instance status.  The operator could be more flexible here and allow for a different subscription name, so long as it installs the same package (operator).

**Comment by marikaj123** [comment]
@mtamboli - Kabanero Operator 0.3.4 does contains the fix.  Please close the issue after SVT verification has completed successfully. Thank you.

**Comment by mtamboli** [comment]
I have verified this defect on operator 0.3.4 and do not see the error.
