### ISSUE TITLE
Install openshift pipelines operator 0.10.1 / triggers 0.2.1

### ISSUE THREAD

**Issue by kaczyns** [kabanero-io/kabanero-operator#407]
For Kabanero release 0.6.0 we need to upgrade to openshift pipelines 0.10.0 so that we can pick up triggers 0.2.x, and with it the fix for kabanero-io/kabanero-foundation#150

**Comment by anneqm** [comment]
Should be the pipelines 0.10.1 release, rather than 0.10.0. 
Dev preview of the openshift-pipeline 0.10.1 is available here: https://github.com/openshift/tektoncd-pipeline/branches and of the openshift-triggers 0.2.1 here: https://github.com/openshift/tektoncd-triggers/branches.  

Expecting the operator by end of the week.

**Comment by kaczyns** [comment]
There is a PR out there for openshift pipelines 0.10.4:
https://github.com/operator-framework/community-operators/pull/1196/files

We can start adding this to our catalog, and then merge it when the community-operators PR merges.

**Comment by kaczyns** [comment]
This was delivered in #455

**Comment by anneqm** [comment]
@kaczyns Does this need to be "redone" when the official release is available, or is from the canary channel accepable?

**Comment by kaczyns** [comment]
@anneqm Typically we look to see if they made any changes between the time they move it from the canary channel to the techpreview channel (or whatever they call it).  They usually will increment the patch version number if they do that, so it's pretty obvious.  If they didn't make any changes, then there's nothing for us to do.
