### ISSUE TITLE
Include the certified Open Liberty Operator

### ISSUE THREAD

**Issue by arthurdm** [kabanero-io/kabanero-operator#426]
The [Open Liberty Operator](https://github.com/OpenLiberty/open-liberty-operator) has been re-launched as a native Go operator, inheriting all of the functionality from the Appsody Operator + adding day-2 operations.  The high level design can be seen [here](https://github.com/OpenLiberty/open-liberty-operator/blob/master/doc/operator-design.md).

This issue tracks the subscription / installation of the Open Liberty Operator by the Kabanero Operator.  

A simple approach is to always install the Open Liberty Operator, in addition to the Appsody Operator.  

A more advanced approach would be for the Kabanero Operator to only install the Open Liberty Operator if a [stack has been configured to use that Operator](https://github.com/appsody/stacks/issues/601).

Please note that there are no collisions between the Open Liberty Operator and the Appsody Operator.  They listen for different CRs (`OpenLibertyApplication` vs `AppsodyApplication`), so they will each work with different deployments.

**Comment by kaczyns** [comment]
Hi @arthurdm - thanks for opening this issue.  My understanding is that we'll do this for the 0.7.0 release of Kabanero.  Please let me know if that's acceptable.

I like the idea of only installing the Open Liberty operator if a stack requires it, but unfortunately this would require the Kabanero operator to directly install another operator, which is frowned upon.  We'll install the Open Liberty operator from the catalog when we install the Appsody operator.

**Comment by dacleyra** [comment]
We have typically taken the following approach

If the APIs that are provided are mature (non-beta/alpha), and the Operator exists in an RH or Certified catalog, then we create a Subscription to that Operator via the RH or Certified catalog. We trust that automatic patch releases into the channel will not break us.

If the APIs that are provided are beta/alpha, we capture the CSV at a tested level and put them in the Kabanero catalog. This ensure that the version does not get automatically upgraded and break us.

Sometimes a channel is just stable/canary
Sometimes a channel is a Minor release stream

OLO is v1beta1

Kabanero Operator will not manage Subscriptions. Bad Idea.
Kabanero Operator will not set `required` APIs in its CSV, due to the current unpredictable nature of what OLM will decide to install.

Even RHOS documentation instructs users to install Operators one-by-one.

Is OLO going to be in the Certified catalog? What Subscription channels will OLO maintain?

**Comment by arthurdm** [comment]
hey @dacleyra - the Open Liberty Operator is already in the certified catalog.  It's using the `beta` channel.   We're planning on having a `1.x` channel once we release 1.0.0 - we're currently iterating over 0.x at the moment, similar to Kabanero.

**Comment by kaczyns** [comment]
@dacleyra lets copy it to our catalog.  with a `beta` channel we can't stop old versions of Kabanero from picking up 0.4 or 0.5 etc.

**Comment by kaczyns** [comment]
This is fixed in #485
