### ISSUE TITLE
Enhance the Kabanero CR operator to support a pipeline yaml file in addition to zips.

### ISSUE THREAD

**Issue by stephenkinder** [kabanero-io/kabanero-operator#451]
As part of the stack-hub design change, we moved pipeline specifications to the Kabanero CR.  The Kabanero CR expects the pipelines to be released and therefore zipped up.   An alternative method for aggregating the pipelines is to stack the pipeline-related CRs in the same file, using the Kubernetes method for concatenating different yamls (each CR separated by `---`).

The Kabanero operator will tolerate either a `.yaml` or `.tar.gz` suffix on the URL specified for pipeline specifications in its CRs.   The Kabanero operator should support either `https` or `github` syntax as well.

Of note, the concatenation is just an alternative way to package the pipelines -- which allows the pipeline engineers to rapidly iterate through development scenarios.   Also of note, the Kabanero pipelines include symbolic processing (e.g. collection-ID) and that same substitution would happen whether the pipeline came from a zip or a concatenated yaml file.

**Comment by kaczyns** [comment]
The stack validating webhook currently enforces that a pipeline zip has a `sha256` set in the Stack CR instance.  @stephenkinder outlines a "rapid development" model above... and computing and setting the `sha256` into the Stack CR on each iteration probably doesn't fall into the "rapid development" category.  

We need the SHA to be there so that when we activate the pipelines, the stack controller can use the digest to figure out if the pipelines/etc have changed, and re-apply them.

One approach we could use is to have the stack mutating webhook check to see if the pipelines are in a yaml file (`.yaml` extension instead of `.tar.gz`).  If it is, and if there is no sha256, then retrieve the file, compute it, and add it to the Stack CR.  Then the validating webhook can remain unchanged, and can enforce that there is a sha256 set.

Another alternative is to relax the validating webhook, such that it only enforces that a sha256 is present if the file ends in a `.tar.gz` extension.  The stack controller then needs to retrieve the yaml file and compute the sha256 before it tries to substitute any of the fill-ins in the pipeline yaml (such as `StackId` or `Digest`).  The template context needs to have the computed sha256 added before the templates are rendered.

**Comment by kaczyns** [comment]
When we activate a stack, the `status` section contains each version of the stack, and for each version we list the individual assets in the pipeline zip (the individual kubernetes objects).  When we add the support for reading the pipelines out of a `.yaml` file, we'll need to change how this works slightly.
*There will no longer be a `manifest.yaml` to use to check the sha256 of the individual assets.  The sha256 will be omitted from the status, and we'll need to make sure that no code depends on this information being there.  More specifically, each asset will be missing `assetDigest`.
* I had originally been concerned that part of the status contained the file name within the `.tar.gz` where the asset yaml was found, but this appears not to be the case.  the individual asset status yaml just contains the name of the object:
```yaml
      - assetDigest: 19afa906601d3a763ac1bd9ab9d0644de86646db33ed6f4e99be30059df2c69b
        assetName: java-microprofile-image-retag-task
        group: tekton.dev
        kind: Task
        namespace: kabanero
        status: active
        version: v1alpha1
```

**Comment by kaczyns** [comment]
@dacleyra I think the development work on this is done - please close this issue if that's true.
