### ISSUE TITLE
Integrate GHE release assets with the http cache

### ISSUE THREAD

**Issue by kaczyns** [kabanero-io/kabanero-operator#470]
Kabanero caches the results of any HTTP GET requests to remote resources, using `etags`.
https://en.wikipedia.org/wiki/HTTP_ETag

When we use the Github API to retrieve release assets, we need to determine if we still receive an `etag` for the remote resource.  These are returned in a header in the HTTP response.  If we still receive one, we should modify our HTTP cache to support this.  Or create a second cache that supports this (I don't think that we'd every cross-use the two caches... if we're going after something using the Github API, we're not going to turn around and start using an `https://` URL to access it).

The existing cache lives in the `pkg/controller/stacks` package, which is wrong, it should be somewhere that can be easily used by the stack controller and the kabanero controller (I guess the current location doesn't preclude any use from any place, but it is confusing as it's used for more than just stacks).  If we're going to use just one cache, then instead of passing in a URL, we'd have to pass in:
1) a key that represents what the resource is.  for https it could be the URL but for github it'd have to be some other string or object
2) An object with some method on it that can get the resource.  For HTTPS this is just the HTTP client but for Github it'd have to be some wrapper object around the HTTP client since the cache wouldn't know what method to call.

The cache would need access to the HTTP request so it could inspect the response headers, and insert the necessary request header.

If we were going to use two caches, most of the wrappering becomes un-necessary.  I like the idea of just one place where we manage etags, but if the implementation gets two complicated, having two would be fine.

**Comment by mezarin** [comment]
Providing a caching mechanism or integrating it with the existing http cache using Etags has a few issues. 

Currently, we use the GitHub Developer APIS to get the release (by tag), find the asset we want, and we download it. The number of http requests to accomplish that are 3. One to get the release (no additional header entries), another one to get download the asset (with an additional required header: “Accept: application/octet-stream"), and a third one to handle the redirect (302) triggered by the download request.

The first time going through the requests has the expected behavior. An Etag is returned on the first and third requests. However, all subsequent requests with the previous Etag set under request header: “If None-Match” show the following behavior:

1. All requests that attempt to get the release receive a response with a status of 200. The Etag in the response is different from the one obtained previously and set under “If None-Match”. Note that the target GitHub repository has not changed.

The expected behavior is that all requests should have received a response with a status of 304.

```
Example showing the unexpected behavior:

Runtime request to get releases:
Trace: Request:  &{GET https://github.ibm.com/api/v3/repos/mezarina/kabanero-stacks/releases/tags/0.6.0 HTTP/1.1 1 1 map[Authorization:[Bearer b8d0c13d0efbdf39ad9ba68404ac92a5c78bfbb1] If-Modified-Since:[Mon, 02 Mar 2020 21:59:57 GMT] If-None-Match:[W/"6c93fd7b43246bbb5e79d2aca21baafa"]] <nil> <nil> 0 [] false github.ibm.com map[] map[] <nil> map[]   <nil> <nil> <nil> 0xc0000ba000}

Trace: Response:  &{200 OK 200 HTTP/1.1 1 1 map[Access-Control-Allow-Origin:[*] Access-Control-Expose-Headers:[ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type] Cache-Control:[private, max-age=60, s-maxage=60] Connection:[keep-alive] Content-Security-Policy:[default-src 'none'] Content-Type:[application/json; charset=utf-8] Date:[Mon, 02 Mar 2020 22:00:38 GMT] Etag:[W/"b7d78fb80bed99f9b736dd2d8d5e4d4d"] Last-Modified:[Mon, 17 Feb 2020 19:12:07 GMT] Referrer-Policy:[origin-when-cross-origin, strict-origin-when-cross-origin] Server:[openresty] Status:[200 OK] Strict-Transport-Security:[max-age=31536000; includeSubdomains] Vary:[Accept, Authorization, Cookie, X-GitHub-OTP] X-Accepted-Oauth-Scopes:[repo] X-Content-Type-Options:[nosniff] X-Frame-Options:[deny] X-Github-Enterprise-Version:[2.17.18] X-Github-Media-Type:[github.v3; format=json] X-Github-Request-Id:[15a95065-4669-40a3-934c-71ea173b945d] X-Oath-Scopes:[repo] X-Ratelimit-Limit:[5000] X-Ratelimit-Remaining:[4998] X-Ratelimit-Reset:[1583189997] X-Runtime-Rack:[0.049312] X-Xss-Protection:[1; mode=block]] 0xc000fa20c0 -1 [chunked] false true map[] 0xc000df3a00 0xc000ab7ef0}

Trace: Request:  &{GET https://github.ibm.com/api/v3/repos/mezarina/kabanero-stacks/releases/tags/0.6.0 HTTP/1.1 1 1 map[Authorization:[Bearer b8d0c13d0efbdf39ad9ba68404ac92a5c78bfbb1] If-Modified-Since:[Mon, 02 Mar 2020 22:00:38 GMT] If-None-Match:[W/"b7d78fb80bed99f9b736dd2d8d5e4d4d"]] <nil> <nil> 0 [] false github.ibm.com map[] map[] <nil> map[]   <nil> <nil> <nil> 0xc0000ba000}

Trace: Response:  &{200 OK 200 HTTP/1.1 1 1 map[Access-Control-Allow-Origin:[*] Access-Control-Expose-Headers:[ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type] Cache-Control:[private, max-age=60, s-maxage=60] Connection:[keep-alive] Content-Security-Policy:[default-src 'none'] Content-Type:[application/json; charset=utf-8] Date:[Mon, 02 Mar 2020 22:00:48 GMT] Etag:[W/"e63e02a8fa828666749a2f2ecf629f4a"] Last-Modified:[Mon, 17 Feb 2020 19:12:07 GMT] Referrer-Policy:[origin-when-cross-origin, strict-origin-when-cross-origin] Server:[openresty] Status:[200 OK] Strict-Transport-Security:[max-age=31536000; includeSubdomains] Vary:[Accept, Authorization, Cookie, X-GitHub-OTP] X-Accepted-Oauth-Scopes:[repo] X-Content-Type-Options:[nosniff] X-Frame-Options:[deny] X-Github-Enterprise-Version:[2.17.18] X-Github-Media-Type:[github.v3; format=json] X-Github-Request-Id:[b4bfa186-3873-4fb3-b296-175682ad2ecb] X-Oauth-Scopes:[repo] X-Ratelimit-Limit:[5000] X-Ratelimit-Remaining:[4996] X-Ratelimit-Reset:[1583189997] X-Runtime-Rack:[0.053625] X-Xss-Protection:[1; mode=block]] 0xc00109c240 -1 [chunked] false true map[] 0xc000df2000 0xc000ab7ef0}
```

What is curious is if header: “Accept: application/octet-stream" is never set when downloading the asset (and we incorrectly just get metadata), all subsequent requests to get the release get a response with the same Etag and a status of 304 as expected (different http clients used).

2. Other issues that may or may not be influenced by setting the required “Accept: application/octet-stream":

a. When a redirect is triggered, the redirect URL is not fixed. It changes every time. The expectation, perhaps unfounded, is that the redirect URL should be the same. If expected, we  can workaround this issue as the differentiating part is the token query parameter.
 
```
Example:
curl -H "Authorization: Bearer b8d0c13d0efbdf39ad9ba68404ac92a5c78bfbb1" -i https://github.ibm.com/api/v3/repos/mezarina/kabanero-stacks/releases/assets/246074 'If-None-Match: "7792d1319ddd9191cb5b2af1a03117ec"' -H "Accept: application/octet-stream"
HTTP/1.1 302 Found
Server: openresty
Date: Mon, 02 Mar 2020 20:01:10 GMT
Content-Type: text/html;charset=utf-8
Content-Length: 0
Connection: keep-alive
X-RateLimit-Limit: 5000
X-RateLimit-Reset: 1583182864
X-RateLimit-Remaining: 4999
Status: 302 Found
location: https://media.github.ibm.com/releases/349918/files/246074?token=AAA_WO8fgeQ5FrfATRXngM1clV3MkGYzks5eXXQWwA%3D%3D
Access-Control-Expose-Headers: ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type
Access-Control-Allow-Origin: *
X-GitHub-Request-Id: a4062919-88dd-46fe-9fdb-7e2b5409e9ae
Strict-Transport-Security: max-age=31536000; includeSubdomains

curl -H "Authorization: Bearer b8d0c13d0efbdf39ad9ba68404ac92a5c78bfbb1" -i https://github.ibm.com/api/v3/repos/mezarina/kabanero-stacks/releases/assets/246074 'If-None-Match: "7792d1319ddd9191cb5b2af1a03117ec"' -H "Accept: application/octet-stream"
HTTP/1.1 302 Found
Server: openresty
Date: Mon, 02 Mar 2020 20:01:13 GMT
Content-Type: text/html;charset=utf-8
Content-Length: 0
Connection: keep-alive
X-RateLimit-Limit: 5000
X-RateLimit-Reset: 1583182864
X-RateLimit-Remaining: 4998
Status: 302 Found
location: https://media.github.ibm.com/releases/349918/files/246074?token=AAA_WDcRK57SZbYWQZM6npJ-1xu_bGknks5eXXQZwA%3D%3D
Access-Control-Expose-Headers: ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type
Access-Control-Allow-Origin: *
X-GitHub-Request-Id: cd362625-c53a-4bad-8a1a-7302a48c9fcf
Strict-Transport-Security: max-age=31536000; includeSubdomains
…
```


b. All redirect requests to download the asset get a response with a 200 status; even though, the Etag set on the request (under “If None-Match”) is the same as the one returned on the response. The expectation here is that all  redirects requests should get a response with a status code of 304. That is because the Etag set on the request under the If None-Match header matches the one in the response.

```
Example:
curl -H "Authorization: Bearer b8d0c13d0efbdf39ad9ba68404ac92a5c78bfbb1" -i  https://media.github.ibm.com/releases/349918/files/246074?token=AAA_WDcRK57SZbYWQZM6npJ-1xu_bGknks5eXXQZwA%3D%3D 'If-None-Match: "2db47f31a99f96ca80a8e5c7bd3368ed048fe48415cf5cd180b88d8766d404ae"'
HTTP/1.1 200 OK
Server: openresty
Date: Mon, 02 Mar 2020 21:47:02 GMT
Content-Type: application/octet-stream
Content-Length: 4811
Connection: keep-alive
Accept-Ranges: bytes
Content-Disposition: attachment; filename=kabanero-index.yaml
Content-Security-Policy: default-src 'none'
Etag: "2db47f31a99f96ca80a8e5c7bd3368ed048fe48415cf5cd180b88d8766d404ae"
Last-Modified: Mon, 17 Feb 2020 19:59:38 GMT
Strict-Transport-Security: max-age=31557600

Runtime redirect request:

Trace: Request: &{GET https://media.github.ibm.com/releases/349918/files/246074?token=AAA_WIrEV02jGhpg01DWyNIAYFCcnEkKks5eXZsRwA%3D%3D HTTP/1.1 1 1 map[If-Modified-Since:[Mon, 02 Mar 2020 22:47:19 GMT] If-None-Match:["2db47f31a99f96ca80a8e5c7bd3368ed048fe48415cf5cd180b88d8766d404ae"]] <nil> <nil> 0 [] false media.github.ibm.com map[] map[] <nil> map[] <nil> <nil> <nil> 0xc0000ba000} 

Trace: Response: &{200 OK 200 HTTP/1.1 1 1 map[Accept-Ranges:[bytes] Connection:[keep-alive] Content-Disposition:[attachment; filename=kabanero-index.yaml] Content-Length:[4811] Content-Security-Policy:[default-src 'none'] Content-Type:[application/octet-stream] Date:[Mon, 02 Mar 2020 22:47:30 GMT] Etag:["2db47f31a99f96ca80a8e5c7bd3368ed048fe48415cf5cd180b88d8766d404ae"] Last-Modified:[Mon, 17 Feb 2020 19:59:38 GMT] Server:[openresty] Strict-Transport-Security:[max-age=31557600] Timing-Allow-Origin:[https://github.ibm.com] X-Content-Type-Options:[nosniff] X-Frame-Options:[deny] X-Github-Request-Id:[cc5008f6-5cd7-11ea-843d-d6410a2fc206] X-Xss-Protection:[1; mode=block]] 0xc000a3c140 4811 [] false false map[] 0xc000d3e600 0xc000bdc000} 
```

Note that the behavior described above is also true if one uses go-github, plain go http requests using just go-github mappings, and if using https://github.com/gregjones/httpcache's, which is the cache recommended by go-github. If were were to use the recommended cache, the number of entries in the memory cache would accumulate due to 2a.

2b has already been asked about here: https://github.community/t5/GitHub-API-Development-and/Codeload-githib-com-ETags-handling/m-p/41509#M3736
I will add another post to that same forum asking about 1a and 2a.

**Comment by kaczyns** [comment]
I've opened a ticket with GitHub support: 590275

There doesn't appear to be any kind of dashboard where you can query the status.  I'll post here with any updates.

Since our experiment was done with GHE, it may be necessary for us to open a ticket with GHE support.  I'll wait and see what GitHub support says first.

**Comment by kaczyns** [comment]
Still no update from Github support.  No way to query the request either.  We may need to resort to some other caching mechanism (limited time-based cache).

**Comment by kaczyns** [comment]
Github support (GHE) support case is here:
https://enterprise.githubsupport.com/hc/en-us/requests/590275

The bottom line is etags are not supported on release assets.  We probed a bit further and support has told us (through experimentation) that the asset ID will change if the asset is updated.  It is not clear if they verified this with development, or just tried it on a test system.

So, it appears the safe thing to do is to cache the asset by ID, for a very short period of time, on the order of a few minutes.  This will allow us to take advantage of the cache when activating all of the stacks.  It's unlikely that an asset would change during this time, but if it did, either it would have a new ID, or very shortly thereafter we'd throw away the old asset from the cache and re-obtain it.

The implementation of this new cache is going to look quite different from the etags cache, with the exception of having a purge time.
