### ISSUE TITLE
Kabanero 0.3.5 csv missing from newer catalog registries

### ISSUE THREAD

**Issue by dacleyra** [kabanero-io/kabanero-operator#528]
This is preventing OLM from building the upgrade graph from an existing 0.3.5 install, when installing newer catalog/version

@kaczyns

**Comment by jgawor** [comment]
there is another level to it i think. 0.4.0 also says
```
  version: 0.4.0
  replaces: kabanero-operator.v0.3.1
``
so even if something is on 0.3.5, it won't be upgraded until we fix this piece as well.

**Comment by kaczyns** [comment]
https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/design/how-to-update-operators.md#skiprange

This is how we handle upgrading from minor release to minor release.  There is no need for the `replaces` to match.  That would be impossible.

I think that what Dan is saying makes sense... if you have 0.3.5 installed, but then suddenly 0.3.5 is not in the catalog, then OLM might get confused.  But with 0.3.5 in the catalog, OLM will be able to compute the path to 0.6.0 because the `skiprange` for 0.4.0 allows you to move from 0.3.x to 0.4.0.

**Comment by marikaj123** [comment]
@dacleyra and @jgawor - Can the issue be verified and closed, please.

**Comment by dacleyra** [comment]
Was not successful with the upgrade process. There is likely more that needs to be done.

**Comment by jgawor** [comment]
I wonder if the upgrade process fails on upgraded 3.1.x clusters. It upgrade process worked ok for me yesterday on 3.1.0.

**Comment by dacleyra** [comment]
On OCP 4.3, It may be that OLM sees that the 0.3.5->0.4.0 is not valid because 0.4.0 CSV does not support OCP 4.3 kube version. Probably need a skiprange or publish 0.4.1, 0.5.1.

**Comment by kaczyns** [comment]
@dacleyra I had not considered that.  I will look at the OLM code and see if it omits choices that don't meet the kube version requirement.  I was pretty sure that they were ignoring the kube version requirement, at least on initial install, but maybe things have changed.

**Comment by kaczyns** [comment]
@dacleyra The kabanero-operator 0.6.0 has the 0.3.5 release information in it.  We've seen the kabanero portion of the upgrade walk thru correctly at least two times after the changes that you've made to the kabanero-catalog.  Please close this issue if you think that the 0.3.5 CSV portion of the general install problems are resolved.

There were a couple of other things touched on here:
1) the `skipRange` which appears to not be an issue based on how we saw the upgrade proceed.
2) the `minKubeVersion` which I've been able to confirm is not a problem.  OLM does check, but since we're specifying 1.14 on kab 0.3, 0.4, and 0.5, and 1.16 on kab 0.6, all versions support OCP 4.3 (which uses 1.16).  The version check should pass for all versions of the operator on OCP 4.3.

**Comment by marikaj123** [comment]
@dacleyra and @jgawor - Can this be verified and closed, accordingly?
