### ISSUE TITLE
Default values for "Governance Policy"

### ISSUE THREAD

**Issue by smcclem** [kabanero-io/kabanero-operator#591]
I tried https://github.com/kabanero-io/kabanero-operator/releases/tag/0.8.0-alpha.1 to try the new "governance policy" section introduced, specifically to test "stack policy". According to the latest design document, there are four possible values for stack policy with one default value:

https://github.com/kabanero-io/kabanero-foundation/blob/master/design/digest.md

When using 0.8.-alpha.1,  I didn't not find any "stack policy" field.   

Shouldn't the value be preset to "active-digest"?   Otherwise all the code in the various places that uses this field would have to assume the default value.  

I just wanted to check this is what was intended and the best way to proceed.

**Comment by kaczyns** [comment]
Hi Scott - the operator doesn't pre-fill-in the default values, because the resulting CR instance would be large and unwieldy.  Not to mention, most users would not fill in most of the values anyway, they would take the defaults.  As an example, take a look at default.yaml and full.yaml in the config/samples directory.  Default is what most people use, and full is what you'd get if we defaulted everything (and technically it's missing some fields which should be there).

If you feel that we need to make it obvious what the governance policy is, by explicitly setting the stackPolicy all the time, then we can do that.  Just please be sure that's what you really want.
@smcclem

**Comment by kaczyns** [comment]
@smcclem I am going to close this issue for now... please re-open it if you need the stack policy to be more explicit.  Thanks!
