### ISSUE TITLE
Update collection status to reflect version update availability

### ISSUE THREAD

**Issue by kyleschlosser** [kabanero-io/kabanero-operator#61]
In addition to the enhancement to digest checking mentioned in #60, the collection status should have an indicator that a version update is available. The update could be qualified using the semantic version, for example be tagged as a "major" update, but this behavior is optional at this time.

**Comment by kaczyns** [comment]
@kyleschlosser It's not clear to me what should happen when an update is available.  It looks like the current collection controller will update the collection regardless of the version, so if there were an update available, it would immediately not be available on the next loop (because it would have been upgraded).  I'm not sure what the desired behavior is.  It may be one of:
1) The controller detects the version in the `index.yaml` has changed from what it has deployed, and waits for someone to update the `spec` to the new version before the update is applied.
2) There is some implied directory structure that I'm not aware of, where multiple versions of the collection can exist simultaneously, and the collection controller should look thru that directory structure and detect that a newer version is available, and then wait for someone to update the `spec` to point to the new version before it is used (at the newer URL).
3) Something else :-)

It seems like the easiest thing to do at this point, is to apply the initial version of the collection, and continue to update it when the collection is updated so long as the version has not changed (ie the digest changed but the version did not change).  Then, when the version does change, the collection `spec` can be updated to indicate that a new version is available, but the new version will not be applied until somone comes and updates the `spec` of the collection to indicate the new version should be used.

What do you think?

**Comment by kaczyns** [comment]
We had several chats with @stephenkinder today.... there are still some details to iron out but I think we have enough information to make progress here.  There will be another update tomorrow.

There is a desire to use a Github release to manage the version of both the `index.yaml` and the various `collection.yaml` documents.  Using a Github release should allow the `Kabanero` document to point to the `index.yaml` defined in a release, and then search for other releases of `index.yaml` in that Github repository and detect when there are newer versions.  It would make sense to display that in the `Kabanero` status.

The individual `collection.yaml` documents will have a version, but the index is already going to point to several versions.  For example, if there is a `microprofile-0.2.1` collection, there may also be a `microprofile-0.2.2` collection in the same index.  Since all collections in the index are installed (at least that's how it's supposed to work for now), there will not be a lot of value in saying that an update is available, because the update would have already been installed alongside the existing version, when the `Kabanero` reads the updated index that points to the new collection version.
