### ISSUE TITLE
Switch image tags to digests

### ISSUE THREAD

**Issue by jgawor** [kabanero-io/kabanero-operator#631]
In addition to #612, all image tags need to be switched to digests (from tags). This and #612 are required for air gap installs.

In OpenShift environment, image mirroring can be set up so that even if operator references image from registry A, the actual image is pulled from registry B. This mirroring is only supported for image references using digests. More information on https://docs.openshift.com/container-platform/4.3/openshift_images/image-configuration.html#images-configuration-registry-mirror_image-configuration

**Comment by kaczyns** [comment]
I think the first hurdle here is going to be re-structuring the build, so that the `kabanero-operator` container is completely built first, pushed, and its digest retrieved.  This will then get inserted into the CSV, at which point the registry can be completely built.

The second hurdle will be changing the way we process `versions.yaml` and how alternate image locations are specified in the Kabanero CR.  The version yaml lets you over-ride based on the tag.  This may still be valid for an over-ride, but the base image is now going to have a digest instead.  I think that means we need to add a field for digest here, and have some logic that allows some combination of digest and/or tag.  Same goes for the Kabanero CR - there will need to be a way to over-ride based on digest instead of tag.  It might be easiest to just scrap the ability to over-ride just the repository or tag, and say that the only way to over-ride is by image name (you get to specify whatever you want, tag or digest or both).  I'm not sure there is a good use case for just specifying the repository or just the tag/digest anymore.

**Comment by marikaj123** [comment]
According to Jarek, not required for Kabanero 0.9.0

**Comment by kaczyns** [comment]
I am closing this - we are building kabanero operator and kabanero operator registry with a repository/digest now.  The version yaml allows the user to over-ride based on image name, which can be `repository@digest`.
