### ISSUE TITLE
Upgrade a collection to a new version and roll back to a prior

### ISSUE THREAD

**Issue by kyleschlosser** [kabanero-io/kabanero-operator#65]
When the version identifier specified in a collection changes, the resources found in the version need to be applied and the status updated. This needs to be done such that the version can later be "rolled back" to the prior. For example, if resources are removed from the collection, those resources need to be removed. This should likely also be recorded in the status so that you can see what resources changed when a version was applied and what the current version is.

**Comment by kaczyns** [comment]
@kyleschlosser after talking with @stephenkinder it sounded like versions of the collections would live alongside each other, so I'm not sure how to handle version changes withing a `Collection` instance.

However I do think we need to keep track of what was applied so that we can delete it when the Collection is deleted.  I'm not sure if we do that with an annotation, a selector, some other way.  I am thinking on it.  It's also possible that I don't understand the collection versioning correctly and that there is a valid case for upgrading an instance of `Collection`.

**Comment by kaczyns** [comment]
What is currently being proposed is that one version of a Collection of a specific type can be active.  The collection repository can have more than one version available (at least the v1 can - it's not clear if the v2 can support this).  So long as the repository contains the old version so that we can go back and retrieve it on the roll back, this issue should be solveable.  It's not clear what to do for v2 yet.

**Comment by kaczyns** [comment]
I am closing this as fixed in #93.
