### ISSUE TITLE
Revisit behavior of registry access failures during stack activation

### ISSUE THREAD

**Issue by smcclem** [kabanero-io/kabanero-operator#715]
Two components are currently relying on the "digest at activation" from the Operator,  pipelines and the command line.   I want to revisit behavior of registry access failures during stack activation.

When this error occurs, it makes it very difficult for the consuming components to determine the appropriate behavior in all the cases and give meaningful error messages to the user, since the issue is occuring in another component outside of the pipelines. 

My desire is that we fail activation of the stack(s) if the registry cannot be accessed at that time. The image registry containing the stack images are a key component of a stack.

**Comment by smcclem** [comment]
There was an issue opened against pipelines that was caused by this issue:  https://github.com/kabanero-io/kabanero-pipelines/issues/378

**Comment by kaczyns** [comment]
I guess the tactical solution here is to fail stack activation if we could not retrieve the digest.

The better solution is to inspect the governance policy and allow the stack to activate if the configuration doesn't care about what the digest is.  I'm not sure if the pipeline will be able to handle that.  It will require the Stack to know what's in the Kabanero CR instance.

**Comment by mtamboli** [comment]
I agree with @kaczyns, if Governance policy is `activeDigest` or `strictDigest` we should fail the activation. In other cases, we should let the activation and pipelines to be successful. There could be reasons when Champ does not care about Governance.

**Comment by dacleyra** [comment]
merged, closing

**Comment by smcclem** [comment]
@kaczyns @mtamboli With respect to activating a stack if the current stackPolicy would not be impacted by the lack of an activation digest, I think the issue here is that the stackPolicy can be altered at any time. I am sure that you could retry the digest if they changed it, but then what would the operator do if it couldn't retrieve the digest?  Disallow the stackPolicy change?  

The container image registry actually contains the stack images that are used for building the applications.  If the image registry is not accessible at any point,  is the stack really active?  Even if we sidestep all stackPolicy issues, the image registry has to be accessible at all times so that we can build applications on them.

**Comment by kaczyns** [comment]
@smcclem I agree with you at the 10,000 foot level, but configuring the operator to retrieve the digest and configuring the pipeline to retrieve the image are two different things, configured two different ways with two different secrets (at least last I checked).  I am saying that we should not fail stack activation just because the operator was not able to read the digest, if the governance policy would not have what the digest was anyway.

If the governance policy changed then the stack controller would have to go retrieve all the stack image digests, and if it couldn't retrieve one, then that stack version would transition from active to error (or inactive or whatever we decided).

I'm trying to save champ the work of creating and labeling/annotating a second secret for the operator to use, it the user doesn't care about the digest.

@stephenkinder maybe you should weigh in here.  I'm happy to back down if I'm being stupid.

**Comment by smcclem** [comment]
@kaczyns Yes, configuring the secrets for the operator and pipelines are two different things.  We talked about a unified registry access service, but I don't think that's even possible (since we don't control access registry access directly in every case i.e. buildah),  but at best I would like to see singular place / service to obtain the configured credentials from.  

Just as an FYI, once this goes in :  https://github.com/kabanero-io/kabanero-pipelines/pull/386 , the pipelines behavior will be:

If the stackPolicy = none,  The operator is not queried for anything.  For any other stack policy, I query the operator for only status="active" stacks, but I do expect the version and digest to be present and valid.  I am not currently validating that the digest is not empty, I assume active = digest is valid and present.  It will use an empty string.
